"""feature request pickup linkage on runs

Revision ID: 0b431f45a3f9
Revises: 561cb26befa4
Create Date: 2026-08-25 00:52:09.452951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b431f45a3f9"
down_revision: str | Sequence[str] | None = "561cb26befa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("feature_request_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "runs", "feature_requests", ["feature_request_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "runs", type_="foreignkey")
    op.drop_column("runs", "feature_request_id")
    # ### end Alembic commands ###
