"""gitea repo url on apps and runs

Revision ID: 110f7f32c0d7
Revises: 0b431f45a3f9
Create Date: 2026-08-25 15:57:43.063091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "110f7f32c0d7"
down_revision: str | Sequence[str] | None = "0b431f45a3f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("repo_url", sa.String(), nullable=True))
    op.add_column("runs", sa.Column("repo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "repo_url")
    op.drop_column("apps", "repo_url")
    # ### end Alembic commands ###
