"""run turn tracking and plan approval

Revision ID: 1857c37697d7
Revises: 9d700c548f48
Create Date: 2026-08-24 21:14:24.904636

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1857c37697d7"
down_revision: str | Sequence[str] | None = "9d700c548f48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("turns_used", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("runs", sa.Column("plan_approved_at", sa.DateTime(), nullable=True))
    op.add_column("runs", sa.Column("requester_sub", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "requester_sub")
    op.drop_column("runs", "plan_approved_at")
    op.drop_column("runs", "turns_used")
    # ### end Alembic commands ###
