"""gate 2 build approval timestamp

Revision ID: 561cb26befa4
Revises: a34929c3ee86
Create Date: 2026-08-25 00:26:11.800270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "561cb26befa4"
down_revision: str | Sequence[str] | None = "a34929c3ee86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("build_approved_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "build_approved_at")
    # ### end Alembic commands ###
