"""build review linkage on runs

Revision ID: a34929c3ee86
Revises: 1857c37697d7
Create Date: 2026-08-24 22:57:58.446387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a34929c3ee86"
down_revision: str | Sequence[str] | None = "1857c37697d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("plan_run_id", sa.UUID(), nullable=True))
    op.add_column("runs", sa.Column("repo_path", sa.String(), nullable=True))
    op.add_column("runs", sa.Column("container_port", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "runs", "runs", ["plan_run_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "runs", type_="foreignkey")
    op.drop_column("runs", "container_port")
    op.drop_column("runs", "repo_path")
    op.drop_column("runs", "plan_run_id")
    # ### end Alembic commands ###
